### PR TITLE
Correct the blog url in navbar

### LINKED ISSUE #66: Incorrect URL linked the the navbar
**Is your feature request related to a problem?**
- In the navbar, item `blog` redirects to an old URL

**Describe the solution you'd like**
- Replace the old URL with the new SEF medium URL `https://sefglobal.medium.com/`

### PR DESCRIPTION
**Pull request by gajindubandara**
## Purpose
The purpose of this PR is to fix #66

## Goals
To replace the new blog URL 

## Approach
Replaced the old URL with https://sefglobal.medium.com/

### Screenshots
Screenshot from 2021-04-25 23-26-45

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Gimhan-minion — DISMISSED** [review]
Thank you @gajindubandara

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
Thank you @gajindubandara, The code looks fine
Got few minor changes on PR best practices though,
1. Commit message convention should be changed, the commit message should be able to fit into the sentence "Once merged this commit will {commit-message}"
ex: Once merged this commit will correct the blog URL in the navbar
2. The PR title should be in the same convention as above

**Comment by gajindubandara** [comment]
> Thank you @gajindubandara, The code looks fine
> Got few minor changes on PR best practices though,
> 
> 1. Commit message convention should be changed, the commit message should be able to fit into the sentence "Once merged this commit will {commit-message}"
>    ex: Once merged this commit will correct the blog URL in the navbar
> 2. The PR title should be in the same convention as above

**Comment by gajindubandara** [comment]
> Thank you @gajindubandara, The code looks fine
> Got few minor changes on PR best practices though,
> 
> 1. Commit message convention should be changed, the commit message should be able to fit into the sentence "Once merged this commit will {commit-message}"
>    ex: Once merged this commit will correct the blog URL in the navbar
> 2. The PR title should be in the same convention as above

@Gravewalker666 Is this ok

**Review by Gravewalker666 — APPROVED** [review]
> @Gravewalker666 Is this ok

Yup, this is great 😀

**Pull request merged**
